// app/(user)/layout.tsx
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
// Remove SanityLive import
import Header from "@/components/Header";
import { AuthProvider } from "@/components/providers/auth-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="flex-1">{children}</main>
        </div>
      </ThemeProvider>
      
      {/* Remove SanityLive component */}
    </AuthProvider>
  );
}